language: php
php:
  - 5.4

script:
  - cd ./public
  - phpunit ./test

notifications:
  email: false
  webhooks:
    urls:
      - https://hall-hooks.herokuapp.com/travis-ci/buildnotification/0b9a16ba6f370c836a998bf0b41a3704
    on_start: always
    on_success: always
    on_failure: always